"""Repository Protocol interfaces — abstract contracts for all data access."""
from typing import Any, Protocol, runtime_checkable


@runtime_checkable
class IUserRepo(Protocol):
    async def create(self, *, id: str, username: str, password_hash: str, email: str | None = None,
                     role: str = "user") -> dict: ...
    async def get(self, user_id: str) -> dict | None: ...
    async def get_by_username(self, username: str) -> dict | None: ...
    async def update(self, user_id: str, **fields) -> dict | None: ...
    async def soft_delete(self, user_id: str) -> None: ...
    async def increment_failed_login(self, user_id: str) -> int: ...
    async def reset_failed_login(self, user_id: str) -> None: ...
    async def lock_until(self, user_id: str, until: str) -> None: ...


@runtime_checkable
class ISessionRepo(Protocol):
    async def create(self, user_id: str, **fields) -> dict: ...
    async def get(self, session_id: str, user_id: str) -> dict | None: ...
    async def list_by_user(self, user_id: str, project_id: str | None = None,
                           offset: int = 0, limit: int = 100) -> list[dict]: ...
    async def update(self, session_id: str, user_id: str, **fields) -> dict | None: ...
    async def soft_delete(self, session_id: str, user_id: str) -> None: ...
    async def count_by_user(self, user_id: str) -> int: ...
    async def count_busy(self, user_id: str) -> int: ...


@runtime_checkable
class IMessageRepo(Protocol):
    async def create(self, user_id: str, **fields) -> dict: ...
    async def get(self, message_id: str) -> dict | None: ...
    async def list_by_session(self, session_id: str) -> list[dict]: ...
    async def update(self, message_id: str, **fields) -> dict | None: ...
    async def sum_cost_this_month(self, user_id: str) -> float: ...


@runtime_checkable
class IPartRepo(Protocol):
    async def create(self, user_id: str, **fields) -> dict: ...
    async def upsert(self, user_id: str, **fields) -> dict: ...
    async def get(self, part_id: str) -> dict | None: ...
    async def list_by_message(self, message_id: str) -> list[dict]: ...
    async def update(self, part_id: str, **fields) -> dict | None: ...


@runtime_checkable
class IPermissionRepo(Protocol):
    async def create_rule(self, user_id: str, **fields) -> dict: ...
    async def list_rules(self, user_id: str, project_id: str | None = None) -> list[dict]: ...
    async def delete_rule(self, rule_id: str, user_id: str) -> None: ...


@runtime_checkable
class IContainerRepo(Protocol):
    async def create(self, user_id: str, **fields) -> dict: ...
    async def get(self, container_id: str, user_id: str) -> dict | None: ...
    async def list_by_user(self, user_id: str, project_id: str | None = None) -> list[dict]: ...
    async def update(self, container_id: str, **fields) -> dict | None: ...
    async def soft_delete(self, container_id: str, user_id: str) -> None: ...
    async def count_by_user(self, user_id: str) -> int: ...


@runtime_checkable
class IPreferenceRepo(Protocol):
    async def get(self, user_id: str) -> dict | None: ...
    async def upsert(self, user_id: str, **fields) -> dict: ...


@runtime_checkable
class IAuditRepo(Protocol):
    async def create(self, user_id: str, action: str, **fields) -> dict: ...
    async def list_by_user(self, user_id: str, offset: int = 0, limit: int = 100) -> list[dict]: ...
