import 'dart:typed_data';

import 'package:flutter/services.dart';

import 'pcm_codec.dart';

/// The call tones (spec §8), generated by ffmpeg into `assets/sounds/` —
/// see the README there. [ringback] is one 1 s ring; the player repeats it
/// with [ringGap] of silence until the call is answered.
enum CallTone {
  ringback,
  ended,
  error;

  String get asset => 'assets/sounds/call_$name.wav';
}

/// Silence after each ring: the Chinese ringback cadence, 1 s on, 4 s off.
const ringGap = Duration(seconds: 4);

/// Decoded tone samples, loaded once per process.
abstract final class CallTones {
  static Future<Map<CallTone, Int16List>>? _loaded;

  static Future<Map<CallTone, Int16List>> load([AssetBundle? bundle]) =>
      _loaded ??= _load(bundle ?? rootBundle).then(
        (tones) => tones,
        onError: (Object error) {
          _loaded = null;
          throw error;
        },
      );

  static Future<Map<CallTone, Int16List>> _load(AssetBundle bundle) async {
    final tones = <CallTone, Int16List>{};
    for (final tone in CallTone.values) {
      final samples = decodeWavPcm16(await bundle.load(tone.asset));
      if (samples != null) tones[tone] = samples;
    }
    return tones;
  }
}
