"""initial_tables

Revision ID: ea9d90d96835
Revises: 
Create Date: 2026-03-01 08:27:41.512082
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers
revision: str = 'ea9d90d96835'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.String(length=26), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('password_hash', sa.String(length=255), nullable=True),
    sa.Column('avatar_url', sa.String(), nullable=True),
    sa.Column('role', sa.String(length=16), server_default='user', nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('oauth_provider', sa.String(length=32), nullable=True),
    sa.Column('oauth_id', sa.String(length=255), nullable=True),
    sa.Column('failed_login_count', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('locked_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('monthly_cost_limit', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_users_email_active', 'users', ['email'], unique=True, postgresql_where=sa.text('email IS NOT NULL AND is_deleted = false'))
    op.create_index('ix_users_oauth', 'users', ['oauth_provider', 'oauth_id'], unique=True, postgresql_where=sa.text('oauth_provider IS NOT NULL'))
    op.create_index('ix_users_username_active', 'users', ['username'], unique=True, postgresql_where=sa.text('is_deleted = false'))
    op.create_table('audit_logs',
    sa.Column('id', sa.String(length=26), nullable=False),
    sa.Column('user_id', sa.String(length=26), nullable=False),
    sa.Column('action', sa.String(length=64), nullable=False),
    sa.Column('resource_type', sa.String(length=32), nullable=True),
    sa.Column('resource_id', sa.String(length=26), nullable=True),
    sa.Column('details', postgresql.JSONB().with_variant(sa.Text(), "sqlite"), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.String(length=512), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_audit_logs_action', 'audit_logs', ['action'], unique=False)
    op.create_index('ix_audit_logs_user_created', 'audit_logs', ['user_id', 'created_at'], unique=False)
    op.create_table('projects',
    sa.Column('id', sa.String(length=26), nullable=False),
    sa.Column('user_id', sa.String(length=26), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('slug', sa.String(length=128), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_projects_user_id', 'projects', ['user_id'], unique=False)
    op.create_index('ix_projects_user_slug_active', 'projects', ['user_id', 'slug'], unique=True, postgresql_where=sa.text('is_deleted = false'))
    op.create_table('prompt_history',
    sa.Column('id', sa.String(length=26), nullable=False),
    sa.Column('user_id', sa.String(length=26), nullable=False),
    sa.Column('content', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_prompt_history_user_created', 'prompt_history', ['user_id', 'created_at'], unique=False)
    op.create_table('user_preferences',
    sa.Column('id', sa.String(length=26), nullable=False),
    sa.Column('user_id', sa.String(length=26), nullable=False),
    sa.Column('theme', sa.String(length=16), server_default='system', nullable=False),
    sa.Column('default_model', sa.String(length=128), nullable=True),
    sa.Column('default_agent', sa.String(length=64), nullable=True),
    sa.Column('default_variant', sa.String(length=32), nullable=True),
    sa.Column('sidebar_open', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('right_panel_open', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('bottom_panel_height', sa.Integer(), server_default='200', nullable=False),
    sa.Column('extra', postgresql.JSONB().with_variant(sa.Text(), "sqlite"), server_default='{}', nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('containers',
    sa.Column('id', sa.String(length=26), nullable=False),
    sa.Column('user_id', sa.String(length=26), nullable=False),
    sa.Column('project_id', sa.String(length=26), nullable=False),
    sa.Column('docker_id', sa.String(length=64), nullable=True),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=True),
    sa.Column('image', sa.String(length=255), nullable=True),
    sa.Column('port', sa.Integer(), nullable=True),
    sa.Column('api_key', sa.String(length=255), nullable=True),
    sa.Column('resource_limits', postgresql.JSONB().with_variant(sa.Text(), "sqlite"), server_default='{}', nullable=False),
    sa.Column('is_deleted', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_containers_docker_id', 'containers', ['docker_id'], unique=True, postgresql_where=sa.text('docker_id IS NOT NULL'))
    op.create_index('ix_containers_port_active', 'containers', ['port'], unique=True, postgresql_where=sa.text('port IS NOT NULL AND is_deleted = false'))
    op.create_index('ix_containers_user_project', 'containers', ['user_id', 'project_id'], unique=False)
    op.create_table('permission_rules',
    sa.Column('id', sa.String(length=26), nullable=False),
    sa.Column('user_id', sa.String(length=26), nullable=False),
    sa.Column('project_id', sa.String(length=26), nullable=True),
    sa.Column('permission', sa.String(length=128), nullable=False),
    sa.Column('pattern', sa.String(length=512), nullable=True),
    sa.Column('action', sa.String(length=16), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_permission_rules_user_project', 'permission_rules', ['user_id', 'project_id'], unique=False)
    op.create_table('sessions',
    sa.Column('id', sa.String(length=26), nullable=False),
    sa.Column('user_id', sa.String(length=26), nullable=False),
    sa.Column('project_id', sa.String(length=26), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('slug', sa.String(length=128), nullable=True),
    sa.Column('agent', sa.String(length=64), nullable=True),
    sa.Column('model', sa.String(length=128), nullable=True),
    sa.Column('status', sa.String(length=16), server_default='idle', nullable=False),
    sa.Column('parent_id', sa.String(length=26), nullable=True),
    sa.Column('token_usage', postgresql.JSONB().with_variant(sa.Text(), "sqlite"), server_default='{}', nullable=False),
    sa.Column('additions', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('deletions', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('files_changed', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('sandbox_id', sa.String(length=64), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['parent_id'], ['sessions.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_sessions_parent', 'sessions', ['parent_id'], unique=False)
    op.create_index('ix_sessions_user_created', 'sessions', ['user_id', 'created_at'], unique=False)
    op.create_index('ix_sessions_user_project_active', 'sessions', ['user_id', 'project_id', 'is_deleted'], unique=False)
    op.create_table('messages',
    sa.Column('id', sa.String(length=26), nullable=False),
    sa.Column('session_id', sa.String(length=26), nullable=False),
    sa.Column('user_id', sa.String(length=26), nullable=False),
    sa.Column('role', sa.String(length=16), nullable=False),
    sa.Column('agent', sa.String(length=64), nullable=True),
    sa.Column('model', sa.String(length=128), nullable=True),
    sa.Column('model_id', sa.String(length=128), nullable=True),
    sa.Column('variant', sa.String(length=32), nullable=True),
    sa.Column('provider_id', sa.String(length=128), nullable=True),
    sa.Column('format', sa.String(length=32), nullable=True),
    sa.Column('system', sa.String(), nullable=True),
    sa.Column('parent_id', sa.String(length=26), nullable=True),
    sa.Column('tokens', postgresql.JSONB().with_variant(sa.Text(), "sqlite"), nullable=True),
    sa.Column('cost', sa.Numeric(precision=12, scale=6), nullable=True),
    sa.Column('finish', sa.String(length=32), nullable=True),
    sa.Column('summary', sa.Boolean(), server_default='false', nullable=True),
    sa.Column('error', postgresql.JSONB().with_variant(sa.Text(), "sqlite"), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_messages_session_created', 'messages', ['session_id', 'created_at'], unique=False)
    op.create_index('ix_messages_user', 'messages', ['user_id'], unique=False)
    op.create_table('todos',
    sa.Column('id', sa.String(length=26), nullable=False),
    sa.Column('session_id', sa.String(length=26), nullable=False),
    sa.Column('user_id', sa.String(length=26), nullable=False),
    sa.Column('items', postgresql.JSONB().with_variant(sa.Text(), "sqlite"), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('session_id')
    )
    op.create_table('parts',
    sa.Column('id', sa.String(length=26), nullable=False),
    sa.Column('message_id', sa.String(length=26), nullable=False),
    sa.Column('session_id', sa.String(length=26), nullable=False),
    sa.Column('user_id', sa.String(length=26), nullable=False),
    sa.Column('type', sa.String(length=32), nullable=False),
    sa.Column('data', postgresql.JSONB().with_variant(sa.Text(), "sqlite"), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['message_id'], ['messages.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_parts_message', 'parts', ['message_id'], unique=False)
    op.create_index('ix_parts_session_type', 'parts', ['session_id', 'type'], unique=False)
    op.create_index('ix_parts_user', 'parts', ['user_id'], unique=False)
    op.create_table('kv_store',
        sa.Column('key', sa.Text(), nullable=False),
        sa.Column('value', sa.Text(), nullable=False),
        sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
        sa.PrimaryKeyConstraint('key')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('kv_store')
    op.drop_index('ix_parts_user', table_name='parts')
    op.drop_index('ix_parts_session_type', table_name='parts')
    op.drop_index('ix_parts_message', table_name='parts')
    op.drop_table('parts')
    op.drop_table('todos')
    op.drop_index('ix_messages_user', table_name='messages')
    op.drop_index('ix_messages_session_created', table_name='messages')
    op.drop_table('messages')
    op.drop_index('ix_sessions_user_project_active', table_name='sessions')
    op.drop_index('ix_sessions_user_created', table_name='sessions')
    op.drop_index('ix_sessions_parent', table_name='sessions')
    op.drop_table('sessions')
    op.drop_index('ix_permission_rules_user_project', table_name='permission_rules')
    op.drop_table('permission_rules')
    op.drop_index('ix_containers_user_project', table_name='containers')
    op.drop_index('ix_containers_port_active', table_name='containers', postgresql_where=sa.text('port IS NOT NULL AND is_deleted = false'))
    op.drop_index('ix_containers_docker_id', table_name='containers', postgresql_where=sa.text('docker_id IS NOT NULL'))
    op.drop_table('containers')
    op.drop_table('user_preferences')
    op.drop_index('ix_prompt_history_user_created', table_name='prompt_history')
    op.drop_table('prompt_history')
    op.drop_index('ix_projects_user_slug_active', table_name='projects', postgresql_where=sa.text('is_deleted = false'))
    op.drop_index('ix_projects_user_id', table_name='projects')
    op.drop_table('projects')
    op.drop_index('ix_audit_logs_user_created', table_name='audit_logs')
    op.drop_index('ix_audit_logs_action', table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_index('ix_users_username_active', table_name='users', postgresql_where=sa.text('is_deleted = false'))
    op.drop_index('ix_users_oauth', table_name='users', postgresql_where=sa.text('oauth_provider IS NOT NULL'))
    op.drop_index('ix_users_email_active', table_name='users', postgresql_where=sa.text('email IS NOT NULL AND is_deleted = false'))
    op.drop_table('users')
    # ### end Alembic commands ###
